server:
  port: 8080
spring:
  application:
    name: portfolio-app

  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://postgres-portfolio:5432/postgres
    username: admin
    password: senha123

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

eureka:
  client:
    service-url:
      defaultZone: http://172.23.0.1:8761/eureka

