server:
  port: 8088
spring:
  application:
    name: portfolio-app

  sql:
    init:
      continue-on-error: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:senha123}

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
eureka:
  client:
    service-url:
      defaultZone: http://172.23.0.1:8761/eureka

