server:
  port: 8080
spring:
  application:
    name: portfolio-app

  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://database-1.ckkwgo0vfhk9.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: senha123

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

